### ISSUE TITLE
I got this error when trying the HostBase demo

### ISSUE THREAD

**Issue by zhangzq71** [StardustDL/RazorComponents.Markdown#100]
I tried it in Ubuntu 20.04, and the log was attached here.
[localhost-1631783255753.log](https://github.com/StardustDL/RazorComponents.Markdown/files/7176475/localhost-1631783255753.log)

**Comment by gregsdennis** [comment]
I'm getting this, too.  (At least I _think_ this is the error that @zhangzq71 is asking about; there are several in the log.)

Specifically:

```
Unhandled exception rendering component: Could not find 'StardustDL_RazorComponents_Markdown.highlight' ('StardustDL_RazorComponents_Markdown' was undefined).
      Error: Could not find 'StardustDL_RazorComponents_Markdown.highlight' ('StardustDL_RazorComponents_Markdown' was undefined).
          at https://localhost:5001/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:1247)
          at b (https://localhost:5001/_framework/blazor.webassembly.js:1:2989)
          at https://localhost:5001/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.10.js:1:190800)
          at do_icall (wasm://wasm/00aba242:wasm-function[10596]:0x194e4e)
```
